/* 
    USER
*/
export const CURRENT_USER = 'CURRENT_USER'
export const FETCH_USER_BY_TOKEN = 'FETCH_USER_BY_TOKEN'
export const SIGN_UP = 'SIGN_UP'
export const PATCH_CURRENT_USER = 'PATCH_CURRENT_USER'
/* 
    ROOMS
*/
export const CREATE_ROOM_REQUEST = "CREATE_ROOM_REQUEST"
export const CREATE_ROOM_SUCCESS = "CREATE_ROOM_SUCCESS"
export const CREATE_ROOM_ERROR = "CREATE_ROOM_ERROR"
export const JOIN_ROOM_REQUEST = "JOIN_ROOM_REQUEST"
export const JOIN_ROOM_SUCCESS = "JOIN_ROOM_SUCCESS"
export const JOIN_ROOM_ERROR = "JOIN_ROOM_ERROR"
export const SET_USERNAME = "SET_USERNAME"
export const SEND_MESSAGE_REQUEST = "SEND_MESSAGE_REQUEST"
export const UPDATE_CHAT_LOG = "UPDATE_CHAT_LOG"